apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-operator-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      registry.operator.elasticsearch: "true"
  template:
    metadata:
      labels:
        registry.operator.elasticsearch: "true"
      name: elasticsearch-operator-registry
    spec:
      initContainers:
      - name: mutate-csv-and-generate-sqlite-db
        image: ${IMAGE_ELASTICSEARCH_OPERATOR_REGISTRY}
        imagePullPolicy: Always
        command:
        - sh
        args:
        - /scripts/registry-init.sh
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: "RuntimeDefault"
        volumeMounts:
        - name: workdir
          mountPath: /bundle
        env:
        - name: IMAGE_ELASTICSEARCH_OPERATOR
          value: ${IMAGE_ELASTICSEARCH_OPERATOR}
        - name: IMAGE_ELASTICSEARCH6
          value: ${IMAGE_ELASTICSEARCH6}
        - name: IMAGE_ELASTICSEARCH_PROXY
          value: ${IMAGE_ELASTICSEARCH_PROXY}
        - name: IMAGE_LOGGING_KIBANA6
          value: ${IMAGE_LOGGING_KIBANA6}
        - name: IMAGE_LOGGING_CURATOR5
          value: ${IMAGE_LOGGING_CURATOR5}

      containers:
      - name: elasticsearch-operator-registry
        image: ${IMAGE_ELASTICSEARCH_OPERATOR_REGISTRY}
        imagePullPolicy: Always
        command:
        - /usr/bin/registry-server
        - --database=/bundle/bundles.db
        volumeMounts:
        - name: workdir
          mountPath: /bundle
        ports:
        - containerPort: 50051
          name: grpc
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - grpc_health_probe
            - -addr=localhost:50051
        readinessProbe:
          exec:
            command:
            - grpc_health_probe
            - -addr=localhost:50051
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: "RuntimeDefault"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      securityContext:
        runAsNonRoot: true
      volumes:
      - name: workdir
        emptyDir: {}
