apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    name: elasticsearch-operator
  name: elasticsearch-operator-alerts
spec:
  groups:
  - name: elasticsearch_operator.alerts
    rules:
    - alert: ElasticsearchOperatorRemovalWarning
      annotations:
        message: Elasticsearch Operator will reach end of life on November 2025.
        summary: IN OCP 4.16 AND FORWARD ELASTICSEARCH and KIBANA ARE NO LONGER SUPPORTED
          FOR LOG STORAGE AND ELASTICSEARCH IS ONLY SUPPORTED FOR SERVICEMESH, TRACING,
          AND KIALI
      expr: |
        last_over_time((max by(version) (csv_succeeded{exported_namespace="openshift-operators-redhat", name=~"elasticsearch-operator.*", version=~"5.8.*"}) * on() group_left() group(cluster_version{version=~"4.1[6-9].*", type="current"}))[5m:]) > 0
      for: 1m
      labels:
        namespace: openshift-operators-redhat
        severity: warning
